services:
  airdrop-iamon99:
    command: ./entry.sh
    labels:
      # TODO: 2023-Jul-12, remove me as no encrypted traffic between cloudflare and my server anymore.
      # - 'traefik.enable=true'
      # - 'traefik.http.routers.share-iamon99-http.rule=Host(`share.iamon99.com`)'
      # - 'traefik.http.routers.share-iamon99-http.entrypoints=web'
      # - 'traefik.http.routers.share-iamon99-http.middlewares=share-iamon99-https'
      # - 'traefik.http.middlewares.share-iamon99-https.redirectscheme.scheme=https'
      # - 'traefik.http.routers.share-iamon99-https.rule=Host(`share.iamon99.com`)'
      # - 'traefik.http.routers.share-iamon99-https.entrypoints=websecure'
      # - 'traefik.http.routers.share-iamon99-https.tls.certresolver=myresolver'
      # - 'traefik.http.services.share-iamon99-https.loadbalancer.server.port=3000'

      - "traefik.enable=true"

      - "traefik.http.routers.share-iamon99.rule=Host(`share.iamon99.com`)"
      - "traefik.http.routers.share-iamon99.entrypoints=web"

      # NOTE: container serving 8080 port
      - "traefik.http.services.share-iamon99.loadbalancer.server.port=3000"

  airdrop-louislabs:
    command: ./entry.sh
    labels:
      # TODO: 2023-Jul-12, remove me as no encrypted traffic between cloudflare and my server anymore.
      # - 'traefik.enable=true'
      # - 'traefik.http.routers.share-louislabs-http.rule=Host(`share.louislabs.com`)'
      # - 'traefik.http.routers.share-louislabs-http.entrypoints=web'
      # - 'traefik.http.routers.share-louislabs-http.middlewares=share-louislabs-https'
      # - 'traefik.http.middlewares.share-louislabs-https.redirectscheme.scheme=https'
      # - 'traefik.http.routers.share-louislabs-https.rule=Host(`share.louislabs.com`)'
      # - 'traefik.http.routers.share-louislabs-https.entrypoints=websecure'
      # - 'traefik.http.routers.share-louislabs-https.tls.certresolver=myresolver'
      # - 'traefik.http.services.share-louislabs-https.loadbalancer.server.port=3000'


      - "traefik.enable=true"

      - "traefik.http.routers.share-louislabs.rule=Host(`share.louislabs.com`)"
      - "traefik.http.routers.share-louislabs.entrypoints=web"

      # NOTE: container serving 8080 port
      - "traefik.http.services.share-louislabs.loadbalancer.server.port=3000"



networks:
  default:
    name: traefik-proxy-network
    external: true
